import http from'node:http';import{readFile}from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';import{Store,id}from'./store.mjs';import{evaluateRun,generateCases,validateContract,validateLab}from'./engine.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),store=new Store(path.resolve(process.env.DATA_DIR||path.join(root,'data')));await store.init();const port=Number(process.env.PORT||3000),mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json'};
async function body(r){let x='';for await(const c of r){x+=c;if(x.length>2e6)throw Object.assign(new Error('Request too large'),{status:413})}return x?JSON.parse(x):{}}function send(r,s,x,t='application/json; charset=utf-8'){r.writeHead(s,{'content-type':t,'cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY'});r.end(t.startsWith('application/json')?JSON.stringify(x):x)}function audit(l,a,actor='user',detail={}){l.audit.push({id:id(),at:new Date().toISOString(),action:a,actor,detail})}
async function route(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/api/health')return send(res,200,{status:'ok',service:'Vehicle API Lab',time:new Date().toISOString()});if(req.method==='GET'&&u.pathname==='/api/labs')return send(res,200,(await store.list()).map(l=>({id:l.id,name:l.name,owner:l.owner,vehicleProgramme:l.vehicleProgramme,updatedAt:l.updatedAt,contracts:l.contracts.length,implementations:l.implementations.length,runs:l.runs.length})));
 if(req.method==='POST'&&u.pathname==='/api/labs'){const x=await body(req),e=validateLab(x);if(e.length)return send(res,400,{errors:e});const l=await store.create({name:x.name.trim(),owner:x.owner.trim(),vehicleProgramme:x.vehicleProgramme.trim(),description:x.description||'',contracts:[],implementations:[],suites:[],runs:[],reviews:[],audit:[]});audit(l,'LAB_CREATED',l.owner);await store.save(l);return send(res,201,l)}
 const m=u.pathname.match(/^\/api\/labs\/([a-f0-9-]+)(?:\/(contracts|implementations|suites|runs|reviews|report))?$/i);if(m&&req.method==='GET'&&!m[2])return send(res,200,await store.get(m[1]));if(!m)return req.method==='GET'?staticFile(u,res):send(res,404,{error:'Not found'});const l=await store.get(m[1]);if(req.method==='GET'&&m[2]==='report'){const run=l.runs.at(-1),suite=run&&l.suites.find(x=>x.id===run.suiteId);return send(res,200,{schemaVersion:'1.0',lab:l,latestEvaluation:run&&suite?evaluateRun(l,suite,run):null})}if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});const x=await body(req);
 if(m[2]==='contracts'){const e=validateContract(x);if(e.length)return send(res,400,{errors:e});const c={id:id(),name:x.name.trim(),version:x.version.trim(),protocol:x.protocol,operation:x.operation.trim(),requestSchema:x.requestSchema||'',responseSchema:x.responseSchema||'',successCode:Number(x.successCode||200),invalidCode:Number(x.invalidCode||400),maxLatencyMs:Number(x.maxLatencyMs||100),timingCritical:Boolean(x.timingCritical),authenticationRequired:Boolean(x.authenticationRequired),idempotent:Boolean(x.idempotent),versionCompatibility:Boolean(x.versionCompatibility),boundaries:x.boundaries||[]};l.contracts.push(c);audit(l,'CONTRACT_ADDED',x.actor,{contractId:c.id})}
 if(m[2]==='implementations'){if(!x.name?.trim()||!x.contractId||!x.target?.trim())return send(res,400,{error:'Implementation name, contract, and target are required.'});const i={id:id(),name:x.name.trim(),contractId:x.contractId,target:x.target.trim(),supplier:x.supplier||'',version:x.version||'',endpoint:x.endpoint||'',environment:x.environment||'LAB'};l.implementations.push(i);audit(l,'IMPLEMENTATION_ADDED',x.actor,{implementationId:i.id})}
 if(m[2]==='suites'){const c=l.contracts.find(v=>v.id===x.contractId);if(!c)return send(res,400,{error:'Contract was not found.'});const s={id:id(),name:x.name?.trim()||`${c.name} conformance`,contractId:c.id,createdAt:new Date().toISOString(),cases:generateCases(c)};l.suites.push(s);audit(l,'SUITE_GENERATED',x.actor,{suiteId:s.id,cases:s.cases.length})}
 if(m[2]==='runs'){const s=l.suites.find(v=>v.id===x.suiteId),i=l.implementations.find(v=>v.id===x.implementationId);if(!s||!i)return send(res,400,{error:'Suite and implementation are required.'});const r={id:id(),suiteId:s.id,implementationId:i.id,executedAt:new Date().toISOString(),environment:x.environment||i.environment,results:Array.isArray(x.results)?x.results:[]};r.evaluation=evaluateRun(l,s,r);l.runs.push(r);audit(l,'RUN_RECORDED',x.actor,{runId:r.id,decision:r.evaluation.decision})}
 if(m[2]==='reviews'){if(!x.reviewer?.trim()||!['APPROVED','REWORK','REJECTED'].includes(x.disposition))return send(res,400,{error:'Reviewer and valid disposition are required.'});const r={id:id(),runId:x.runId||l.runs.at(-1)?.id,reviewer:x.reviewer.trim(),disposition:x.disposition,notes:x.notes||'',at:new Date().toISOString()};l.reviews.push(r);audit(l,'REVIEW_RECORDED',r.reviewer,{reviewId:r.id,disposition:r.disposition})}
 await store.save(l);return send(res,200,l)}
async function staticFile(u,res){const f=u.pathname==='/'?'index.html':u.pathname.replace(/^\/+/,''),t=path.join(root,'public',path.normalize(f));if(!t.startsWith(path.join(root,'public')))return send(res,403,{error:'Forbidden'});try{return send(res,200,await readFile(t),mime[path.extname(t)]||'application/octet-stream')}catch{return send(res,404,{error:'Not found'})}}
http.createServer((q,s)=>route(q,s).catch(e=>{console.error(e);send(s,e.status||500,{error:e.message||'Unexpected error'})})).listen(port,'0.0.0.0',()=>console.log(`Vehicle API Lab listening on ${port}`));
